// Generated by protoc-gen-dart. DO NOT EDIT.
// source: protos/models.proto

// ignore_for_file: annotate_overrides, camel_case_types // ignore_for_file: constant_identifier_names, library_prefixes // ignore_for_file: non_constant_identifier_names, prefer_final_fields // ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:core' as $core;

import 'package:fixnum/fixnum.dart' as $fixnum;
import 'package:protobuf/protobuf.dart' as $pb;

class HazardMarker extends $pb.GeneratedMessage {
  factory HazardMarker({
    $core.String? id,
    $core.double? latitude,
    $core.double? longitude,
    $core.String? type,
    $core.String? description,
    $fixnum.Int64? timestamp,
    $core.String? senderId,
    $core.String? signature,
    $core.int? trustTier,
  }) {
    final result = create();
    if (id != null) result.id = id;
    if (latitude != null) result.latitude = latitude;
    if (longitude != null) result.longitude = longitude;
    if (type != null) result.type = type;
    if (description != null) result.description = description;
    if (timestamp != null) result.timestamp = timestamp;
    if (senderId != null) result.senderId = senderId;
    if (signature != null) result.signature = signature;
    if (trustTier != null) result.trustTier = trustTier;
    return result;
  }

  HazardMarker._() : super();

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(
    const $core.bool.fromEnvironment('protobuf.omit_message_names') ? '' : 'HazardMarker',
    package: const $pb.PackageName(
      const $core.bool.fromEnvironment('protobuf.omit_message_names') ? '' : 'floodio',
    ),
    createEmptyInstance: create,
  )
    ..aOS(1, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'id')
    ..a<$core.double>(2, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'latitude', $pb.PbFieldType.OD)
    ..a<$core.double>(3, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'longitude', $pb.PbFieldType.OD)
    ..aOS(4, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'type')
    ..aOS(5, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'description')
    ..aInt64(6, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'timestamp')
    ..aOS(7, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'senderId')
    ..aOS(8, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'signature')
    ..a<$core.int>(9, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'trustTier', $pb.PbFieldType.O3)
    ..hasRequiredFields = false;

  @$core.override
  HazardMarker createEmptyInstance() => create();

  static HazardMarker create() => HazardMarker._();

  @$core.override
  $pb.BuilderInfo get info_ => _i;

  @$core.override
  HazardMarker clone() => HazardMarker()..mergeFromMessage(this);

  @$core.override
  $pb.GeneratedMessage createEmptyInstance_() => create();

  static $pb.PbList<HazardMarker> createRepeated() => $pb.PbList<HazardMarker>();

  @$core.pragma('dart2js:noInline')
  static HazardMarker getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<HazardMarker>(create);
  static HazardMarker? _defaultInstance;

  @$pb.TagNumber(1)
  $core.String get id => $_getSZ(0);
  @$pb.TagNumber(1)
  set id($core.String v) { $_setString(0, v); }
  @$pb.TagNumber(1)
  $core.bool hasId() => $_has(0);
  @$pb.TagNumber(1)
  void clearId() => clearField(1);

  @$pb.TagNumber(2)
  $core.double get latitude => $_getN(1);
  @$pb.TagNumber(2)
  set latitude($core.double v) { $_setDouble(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasLatitude() => $_has(1);
  @$pb.TagNumber(2)
  void clearLatitude() => clearField(2);

  @$pb.TagNumber(3)
  $core.double get longitude => $_getN(2);
  @$pb.TagNumber(3)
  set longitude($core.double v) { $_setDouble(2, v); }
  @$pb.TagNumber(3)
  $core.bool hasLongitude() => $_has(2);
  @$pb.TagNumber(3)
  void clearLongitude() => clearField(3);

  @$pb.TagNumber(4)
  $core.String get type => $_getSZ(3);
  @$pb.TagNumber(4)
  set type($core.String v) { $_setString(3, v); }
  @$pb.TagNumber(4)
  $core.bool hasType() => $_has(3);
  @$pb.TagNumber(4)
  void clearType() => clearField(4);

  @$pb.TagNumber(5)
  $core.String get description => $_getSZ(4);
  @$pb.TagNumber(5)
  set description($core.String v) { $_setString(4, v); }
  @$pb.TagNumber(5)
  $core.bool hasDescription() => $_has(4);
  @$pb.TagNumber(5)
  void clearDescription() => clearField(5);

  @$pb.TagNumber(6)
  $fixnum.Int64 get timestamp => $_getI64(5);
  @$pb.TagNumber(6)
  set timestamp($fixnum.Int64 v) { $_setInt64(5, v); }
  @$pb.TagNumber(6)
  $core.bool hasTimestamp() => $_has(5);
  @$pb.TagNumber(6)
  void clearTimestamp() => clearField(6);

  @$pb.TagNumber(7)
  $core.String get senderId => $_getSZ(6);
  @$pb.TagNumber(7)
  set senderId($core.String v) { $_setString(6, v); }
  @$pb.TagNumber(7)
  $core.bool hasSenderId() => $_has(6);
  @$pb.TagNumber(7)
  void clearSenderId() => clearField(7);

  @$pb.TagNumber(8)
  $core.String get signature => $_getSZ(7);
  @$pb.TagNumber(8)
  set signature($core.String v) { $_setString(7, v); }
  @$pb.TagNumber(8)
  $core.bool hasSignature() => $_has(7);
  @$pb.TagNumber(8)
  void clearSignature() => clearField(8);

  @$pb.TagNumber(9)
  $core.int get trustTier => $_getIZ(8);
  @$pb.TagNumber(9)
  set trustTier($core.int v) { $_setSignedInt32(8, v); }
  @$pb.TagNumber(9)
  $core.bool hasTrustTier() => $_has(8);
  @$pb.TagNumber(9)
  void clearTrustTier() => clearField(9);
}

class NewsItem extends $pb.GeneratedMessage {
  factory NewsItem({
    $core.String? id,
    $core.String? title,
    $core.String? content,
    $fixnum.Int64? timestamp,
    $core.String? senderId,
    $core.String? signature,
    $core.int? trustTier,
  }) {
    final result = create();
    if (id != null) result.id = id;
    if (title != null) result.title = title;
    if (content != null) result.content = content;
    if (timestamp != null) result.timestamp = timestamp;
    if (senderId != null) result.senderId = senderId;
    if (signature != null) result.signature = signature;
    if (trustTier != null) result.trustTier = trustTier;
    return result;
  }

  NewsItem._() : super();

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(
    const $core.bool.fromEnvironment('protobuf.omit_message_names') ? '' : 'NewsItem',
    package: const $pb.PackageName(
      const $core.bool.fromEnvironment('protobuf.omit_message_names') ? '' : 'floodio',
    ),
    createEmptyInstance: create,
  )
    ..aOS(1, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'id')
    ..aOS(2, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'title')
    ..aOS(3, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'content')
    ..aInt64(4, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'timestamp')
    ..aOS(5, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'senderId')
    ..aOS(6, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'signature')
    ..a<$core.int>(7, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'trustTier', $pb.PbFieldType.O3)
    ..hasRequiredFields = false;

  @$core.override
  NewsItem createEmptyInstance() => create();

  static NewsItem create() => NewsItem._();

  @$core.override
  $pb.BuilderInfo get info_ => _i;

  @$core.override
  NewsItem clone() => NewsItem()..mergeFromMessage(this);

  @$core.override
  $pb.GeneratedMessage createEmptyInstance_() => create();

  static $pb.PbList<NewsItem> createRepeated() => $pb.PbList<NewsItem>();

  @$core.pragma('dart2js:noInline')
  static NewsItem getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<NewsItem>(create);
  static NewsItem? _defaultInstance;

  @$pb.TagNumber(1)
  $core.String get id => $_getSZ(0);
  @$pb.TagNumber(1)
  set id($core.String v) { $_setString(0, v); }
  @$pb.TagNumber(1)
  $core.bool hasId() => $_has(0);
  @$pb.TagNumber(1)
  void clearId() => clearField(1);

  @$pb.TagNumber(2)
  $core.String get title => $_getSZ(1);
  @$pb.TagNumber(2)
  set title($core.String v) { $_setString(1, v); }
  @$pb.TagNumber(2)
  $core.bool hasTitle() => $_has(1);
  @$pb.TagNumber(2)
  void clearTitle() => clearField(2);

  @$pb.TagNumber(3)
  $core.String get content => $_getSZ(2);
  @$pb.TagNumber(3)
  set content($core.String v) { $_setString(2, v); }
  @$pb.TagNumber(3)
  $core.bool hasContent() => $_has(2);
  @$pb.TagNumber(3)
  void clearContent() => clearField(3);

  @$pb.TagNumber(4)
  $fixnum.Int64 get timestamp => $_getI64(3);
  @$pb.TagNumber(4)
  set timestamp($fixnum.Int64 v) { $_setInt64(3, v); }
  @$pb.TagNumber(4)
  $core.bool hasTimestamp() => $_has(3);
  @$pb.TagNumber(4)
  void clearTimestamp() => clearField(4);

  @$pb.TagNumber(5)
  $core.String get senderId => $_getSZ(4);
  @$pb.TagNumber(5)
  set senderId($core.String v) { $_setString(4, v); }
  @$pb.TagNumber(5)
  $core.bool hasSenderId() => $_has(4);
  @$pb.TagNumber(5)
  void clearSenderId() => clearField(5);

  @$pb.TagNumber(6)
  $core.String get signature => $_getSZ(5);
  @$pb.TagNumber(6)
  set signature($core.String v) { $_setString(5, v); }
  @$pb.TagNumber(6)
  $core.bool hasSignature() => $_has(5);
  @$pb.TagNumber(6)
  void clearSignature() => clearField(6);

  @$pb.TagNumber(7)
  $core.int get trustTier => $_getIZ(6);
  @$pb.TagNumber(7)
  set trustTier($core.int v) { $_setSignedInt32(6, v); }
  @$pb.TagNumber(7)
  $core.bool hasTrustTier() => $_has(6);
  @$pb.TagNumber(7)
  void clearTrustTier() => clearField(7);
}

class SyncPayload extends $pb.GeneratedMessage {
  factory SyncPayload({
    $core.Iterable<HazardMarker>? markers,
    $core.Iterable<NewsItem>? news,
  }) {
    final result = create();
    if (markers != null) result.markers.addAll(markers);
    if (news != null) result.news.addAll(news);
    return result;
  }

  SyncPayload._() : super();

  static final $pb.BuilderInfo _i = $pb.BuilderInfo(
    const $core.bool.fromEnvironment('protobuf.omit_message_names') ? '' : 'SyncPayload',
    package: const $pb.PackageName(
      const $core.bool.fromEnvironment('protobuf.omit_message_names') ? '' : 'floodio',
    ),
    createEmptyInstance: create,
  )
    ..pc<HazardMarker>(1, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'markers', $pb.PbFieldType.PM, subBuilder: HazardMarker.create)
    ..pc<NewsItem>(2, const $core.bool.fromEnvironment('protobuf.omit_field_names') ? '' : 'news', $pb.PbFieldType.PM, subBuilder: NewsItem.create)
    ..hasRequiredFields = false;

  @$core.override
  SyncPayload createEmptyInstance() => create();

  static SyncPayload create() => SyncPayload._();

  @$core.override
  $pb.BuilderInfo get info_ => _i;

  @$core.override
  SyncPayload clone() => SyncPayload()..mergeFromMessage(this);

  @$core.override
  $pb.GeneratedMessage createEmptyInstance_() => create();

  static $pb.PbList<SyncPayload> createRepeated() => $pb.PbList<SyncPayload>();

  @$core.pragma('dart2js:noInline')
  static SyncPayload getDefault() => _defaultInstance ??= $pb.GeneratedMessage.$_defaultFor<SyncPayload>(create);
  static SyncPayload? _defaultInstance;

  @$pb.TagNumber(1)
  $core.List<HazardMarker> get markers => $_getList(0);

  @$pb.TagNumber(2)
  $core.List<NewsItem> get news => $_getList(1);
}
