name: floodio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cryptography: ^2.9.0
  cryptography_flutter: ^2.3.4
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  device_info_plus: ^11.3.0
  fixnum: ^1.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  protobuf: ^6.0.0
  riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  shared_preferences: ^2.3.2
  flutter_ble_peripheral: ^2.1.0
  flutter_p2p_connection: ^3.0.3
  flutter_blue_plus: ^2.2.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.13.0
  riverpod_generator: ^4.0.3
  drift_dev: ^2.31.0
  protoc_plugin: ^25.0.0

flutter:
  uses-material-design: true
